version: 2


references:
  workspace_root: &workspace_root
    /home/circleci/project

  node_image: &node_image
    circleci/node:8.9

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  node_config: &node_config
    docker:
      - image: *node_image
    working_directory: *workspace_root

  yarn_cache_restore: &yarn_cache_restore
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-

  yarn_install: &yarn_install
    run: yarn install --prefer-offline --frozen-lockfile

  yarn_cache_save: &yarn_cache_save
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build-test:
    <<: *node_config
    steps:
      - checkout
      - *yarn_cache_restore
      - *yarn_install
      - *yarn_cache_save
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - lib
            - package.json
  
  publish:
    <<: *node_config
    steps:
      - *attach_workspace
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
    
    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test
      - publish:
          requires:
            - build-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
